### ISSUE TITLE
Calling the class - can you help me?

### ISSUE THREAD

**Issue by staebchen0** [nathancy/stackoverflow#1]
Capture multiple camera streams - great example :-) 
I am brand new and I am not very familiar with classes. I use Visual Studio and imported your example as a class (class_Multicam.py).

Can you tell me how and what to call first from my main script?

And do I have to update the frame afterwards via the class?

MainProgram.py

Import class_Multicam
#And then? Call first Cam...

Do you have an example of how to use the class from the main program?

**Comment by staebchen0** [comment]
since PyQt4 is not supported, I installed PyQt5 (windows)
Change:
```
class CameraWidget(QtGui.QWidget): in
class CameraWidget(QtWidgets.QWidget):
```

I have now tried the following:

Call:
```
stream_link = "rtsp: // user: Pw@192.168.2.127: 554 / stream = 0"
ipcam = class_echtzeitIPCam.CameraWidget (600,600, stream_link)
```

The program crashes without an error message, in line:
` super (CameraWidget, self) .__ init __ (parent)`

**Comment by nathancy** [comment]
You should open a question on stackoverflow where many eyes will see it :)

**Comment by staebchen0** [comment]
okay thanks! but unfortunately no one answers, so I thought I would ask the creator directly.
